inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-performance

Performance:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Style/SpecialGlobalVars:
  Enabled: false
