require: rubocop-performance

Performance:
  Enabled: true

AllCops:
  NewCops: enable

Style/SpecialGlobalVars:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
